# Site settings
title: Wideplum Blog
header-img: img/home-bg.jpg
email: wideplum@163.com
description: "产品经理／百度 "
baseurl: ""
url: "http://wideplum.github.io"
twitter_username: huxpro
github_username:  huxpro
facebook_username:  huxpro
weibo_username: huxpro
zhihu_username: huxpro

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
